server:
  port: 8082
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:   #client的服务名
    name: chen-cloud-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TPACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TPACE
    com.itmuchL: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#添加对该服务的描述信息
info:
  app.name: movie
  company.name: www.chen1.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$