server:
  port: 8762

#eureka配置首页System Status信息和其他eureka的相互注册
eureka:
  datacenter: cloud            #eureka首页的System Status
  environment: product         #eureka首页的System Status
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true  #是否将自己注册到eureka中，默认为true
    fetchRegistry: true         #是否从eureka中获取注册信息
    serviceUrl:
      #eureka客户端与服务端进行交互的地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8764/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port} #:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  dashboard:   # 修改eureka的默认主页访问路径
    enabled: true
    path: /chen

#项目名(eureka注册的模块名称)
spring:
  application:
    name: chen-cloud-eureka